### PR TITLE
support for millisecond-precise time inputs for jday

### PR DESCRIPTION
**Pull request by davidcalhoun**
Based on #32, with some extra testing goodies this time.  :)

### CODE REVIEW

**Comment by ezze** [comment]
@davidcalhoun, thanks a lot for your new pull request!

Are you sure that your new tests will pass when `now.getUTCMilliseconds()` returns 0?

I also want to ask you to look at new `invjday` function I ported from original Python library and check whether it's possible to add milliseconds support there.

**Comment by ezze** [comment]
Probably it's better to use predefined dates for testing instead of `new Date()`.

**Comment by davidcalhoun** [comment]
Thanks for having a look.  Will try to address your comments later this evening.

**Comment by ezze** [comment]
@davidcalhoun, have you any chance to look at this soon? Let me know if you to finish this task by yourself, or I'll try continue with my own efforts.

**Comment by davidcalhoun** [comment]
Ack, sorry I didn't make time for this :(.  If you want to have a shot at it and have more time than me, go for it.  :) . I won't mind if you close this.

**Comment by ezze** [comment]
@davidcalhoun, thanks a lot for your contribution again. I merged this with minor test fixes.

**Pull request merged**
