### PR TITLE
JavaScript Date is supported as function argument of jday, gstimeFromDate and propagate

### PR DESCRIPTION
**Pull request by ezze**
I was tired to write something like this each time:

    var date = new Date();
    var result = satellite.propagate(
        satrec,
        date.getUTCFullYear(),
        date.getUTCMonth() + 1,
        date.getUTCDate(),
        date.getUTCHours(),
        date.getUTCMinutes(),
        date.getUTCSeconds()
    );

and keep in mind that I should add (or subtract?) 1 to months.

With this pull request things become easier:

    var date = new Date(),
        gmst = satellite.gstimeFromDate(date),
        jday = satellite.jday(date),
        result = satellite.propagate(satrec, date);

though old behavior is also preserved.

Hope it will be accepted and published to NPM and Bower as new version so I can update and use it in our projects.

Cheers! 

>

### CODE REVIEW

**Comment by ezze** [comment]
@shashwatak, could you, please, revise this?

**Comment by shashwatak** [comment]
@ezze thanks for the update! I'm going to review it now.

**Comment by shashwatak** [comment]
Hey, not sure if the bower package update worked as planned. It should be 1.3.0 now.

**Comment by ezze** [comment]
With `bower info satellite.js` I see that `1.3.0` is available (did you forget to update version `1.2.0` to `1.3.0` in `README.md` and scripts?

What about NPM? I still see `1.2.0` only [https://www.npmjs.com/package/satellite.js]. As far as I know you should publish each new version with `npm publish`.

**Comment by ezze** [comment]
@shashwatak, please, release NPM version.

**Comment by shashwatak** [comment]
@ezze sorry! Done (I think). Let me know if it worked.

**Comment by ezze** [comment]
@shashwatak, thanks a lot. NPM package works for me!

**Pull request merged**
