### PR TITLE
Commonjs support

### PR DESCRIPTION
**Pull request by ezze**
This pull request introduces another big code refactoring and allows to require the library in Node.js and CommonJS-like environments. The following global changes are made:

- source code in `src` is ported from RequireJS (AMD) modules to CommonJS modules and uses ES6 syntax;
- source code is transpiled to ES5 in `lib` with [Babel 6](https://babeljs.io/) — the resulting library can be required from Node.js with `require('satellite.js')`;
- due to RequireJS is not used anymore we don't need Phantom.js for testing...so tests are rewritten with [Mocha](https://mochajs.org/) and [Chai](http://chaijs.com/);
- the final `dist` is built from transpiled `lib` as [UMD module](https://github.com/umdjs/umd) with [Webpack 2](https://webpack.js.org/) — this should allow to use the library in any environment: CommonJS, AMD, script tag;
- JSHint is replaced by [ESLint](http://eslint.org/) with [Airbnb shared configuration](https://www.npmjs.com/package/eslint-config-airbnb) which has a set of rich rules to validate ES6 code (it was the most difficult part to implement, allowed to remove some unused variables...hopefully, nothing is broken, at least tests are passed);
- copyright text from `copyright.txt` file is prepended as comment header to all `lib` and `dist` files automatically (there is no need to fix it manually anymore);
- all build and test tasks are [NPM scripts](https://docs.npmjs.com/misc/scripts) now (bye-bye Grunt);
- `README.md` is also updated.

I didn't test it yet in Node but requiring it like (`main` in `package.json`):

    var satellite = require('./lib/index');

works for me. A zip package created with

    npm pack

also seems good.

I also have access to global `satellite` object in a browser:

    <html>
        <head>
            <script src="satellite.js"></script>
            <script>console.log(satellite);</script>
        </head>
        <body></body>
    </html>

Hope that Bower configuration is also not broken.

### CODE REVIEW

**Comment by ezze** [comment]
Another important note! `sgp4` and `sgp4init` functions don't alter `satrec` argument anymore because it's considered as bad practice. Instead, `satrec` is cloned and returned as result of `sgp4init` and `satrec` property of result object of `sgp4`.

**Comment by ezze** [comment]
Should fix #22

**Comment by ezze** [comment]
Dear @shashwatak, please come with some feedback whether you will revise it or not. If not then we will consider creating an npm package of our fork because current implementation doesn't allow us to use the library in Node.js-way.

As temporary workaround I rely on Webpack's AMD support and require the lib like this:

    import {satellite} from 'satellite.js';

**Comment by battlesnake** [comment]
Probably worth forking, I sent a PR a year ago to enable support for Browserify, and nothing happened.

**Pull request merged**
