### PR TITLE
Webworker

### PR DESCRIPTION
**Pull request by TJKoury**
Starting a branch with embedded source to enable easy web worker initialization.  Future additions will include a simple web worker API.  To create a webworker after import (at the moment, will simply create satellite-js instance within worker thread):

var satellite-worker = new Worker(URL.createObjectURL(new Blob([satellite._src])));

To test append "console.log(satellite.version)" to the end of satellite._src:

var satellite-worker = new Worker(URL.createObjectURL(new Blob([satellite._src+"console.log(satellite.version)"])));

The version should pop up in the console.

Uses NodeJS to build.  Run 'npm install' (which will also 'npm run build').

### CODE REVIEW

**Comment by shashwatak** [comment]
Awesome!

A few issues though:
1) don't include the build result "satellite.js" file in the repo. This name conflicts with the existing build artifact, and the output is minified JS which is not readable or editable. Doesn't make sense to track it with version control.
2) README.md needs to be updated to reflect this new feature. Explain how to build and use this feature.
3) Would it be possible to remove the dependency on node? I'd like to keep the outside dependencies to a minimum.

Thanks for your work =) Excited to have this feature be part of this library.

**Comment by TJKoury** [comment]
Thanks for the quick response; will definitely update the README,md.

Issues 1 & 3 are related; I intentionally had the build target included and
added a package.json with "main" being the build target so that it can be
required in the CommonJS format for use with NodeJS.  The tag at the end of
the file detects whether or not it's being run in Node or in the browser.

For an example, this guy:

https://github.com/joshuaferrara/node-sgp4

is doing an incomplete version of a node port, makes more sense to just use
your work in both client and server.  I'll make sure the multi-threading
code is able to be used in Node, as well.  Eventually I'm going to build a
node-gyp C++ version and have NodeJS defer to that compiled version when a
flag is set, but one step at a time.

As far as needing Node vs make as a build requirement, I find myself on
Windows boxes often which means that having a version of Node around is
easier than installing/juggling MinGW/gcc make/VS make/nmake, especially
when I don't have install permissions.

If this doesn't seem like the direction you'd like to go I'll cancel the
pull and just develop it as my own fork.  Thanks again for taking the time
to pull this together, it's a big time saver.

**Comment by shashwatak** [comment]
Thanks TJ. I'm still debating on how to proceed. Frankly, I'm not knowledgable enough about these frameworks to know if integration is a good idea or not. Need to do more research and I'll let you know soon =)

**Comment by shashwatak** [comment]
I will not be pulling this request. Sorry about that =(

I want to keep this project as simple as possible, thus allowing folks like you to fork and do interesting things with it. If we start adding too many features and requirements, it will raise the barrier to entry and modification.

Thanks again! I appreciate the effort you put into this PR =)

**Comment by wenzul** [comment]
> I want to keep this project as simple as possible

+1

**Comment by TJKoury** [comment]
No problem.  I will try and make the web worker code as standalone as possible for future integration.

**Pull request closed without merging**
