### PR TITLE
Increased test coverage for fringe cases

### PR DESCRIPTION
**Pull request by thkruz**
Tried to add some more coverage on the fringe cases. I want to look into issue #75 but would prefer 100% code coverage first.

### CODE REVIEW

**Comment by thkruz** [comment]
Looks like I need to double check the eslint setup...

**Comment by ezze** [comment]
@thkruz Wow, cool! Increasing test coverage is what we could only dream about.

**Comment by ezze** [comment]
@thkruz How are you doing? :) Should we close it?

**Comment by thkruz** [comment]
@ezze I have been really busy and just now getting back on github/coding. This PR was good to go back in Jan. I would think you want to merge it, not close it.

**Comment by ezze** [comment]
@thkruz No problems, dude! Can you address my notes regarding `toBeCloseTo` and `compareVectors` mentioned above?

**Comment by thkruz** [comment]
@ezze maybe I am going crazy, but I don't see any notes from you regarding those functions? On my end it shows no reviews of the commits... Can you point me in the right direction?

**Review by ezze — CHANGES_REQUESTED** [review]

**Comment by ezze** [comment]
@thkruz Sorry, my bad. I started code review but didn't submit changes request.

**Comment by thkruz** [comment]
Had to start PR #91 in order to make the requested changes. Closing this.

**Pull request closed without merging**
