### PR TITLE
Reorganizing project with Require.js, Grunt, Bower, Jasmine and JSHint

### PR DESCRIPTION
**Pull request by ezze**
The project is reorganized as described in https://github.com/shashwatak/satellite-js/issues/12.

I updated `README.md`, `bower.json` and `package.json` assuming that you will register a Bower package with `satellite.js` name:

    bower register satellite.js git://github.com/shashwatak/satellite-js

If you want to give it another name you should update these files before creating [semantic version tag](http://semver.org/) for Bower. My fork is already registered as `satellitejs` and if you want to use this name I need to unregister it first (let me know if it's that case). When you register you Bower package I will be happy to update my project to use it and unregister `satellitejs`.

Read more about registering Bower packages [here](http://bower.io/docs/creating-packages/#register).

### CODE REVIEW

**Comment by shashwatak** [comment]
I would love to register this project in bower, let me know once you've unregistered, and I'll register and merge the PR!

**Comment by ezze** [comment]
I unregistered `satellitejs`. Don't forget to update `README.md` by changing:

    bower install satellite.js

to

    bower install satellitejs

And change `satellite.js` to `satellitejs` in `bower.json` and `package.json` then.

**Comment by shashwatak** [comment]
I can't decide if I want to register the project as

satellitejs
satellite-js
satellite.js

What do you recommend? What is best practice?

**Comment by shashwatak** [comment]
I'm gonna go with "satellite.js", seems to be a common practice, and it matches the names I've been using thus far.

**Comment by ezze** [comment]
Hey, I think it's the question of taste. E.g. Three.js library is named as `threejs` while LESS is named as `less.js`. I would also prefer a name with or without dot so `satellite.js` is a nice choice! ;)

**Comment by shashwatak** [comment]
Done! Thanks again @ezze! 

How long before the bower registry updates? Looking at bower.heroku.com, I still don't see it.

**Comment by ezze** [comment]
Run

    bower info satellite.js

from command line and you'll it's there but there is no available versions. Did you forget a semver tag `1.2.0`?

**Comment by shashwatak** [comment]
yep, lol. fixed.

**Comment by shashwatak** [comment]
OK, bower info now shows an available version (1.2.0), but I still don't see it in bower.heroku.com, but I suppose that will update shortly.

**Comment by ezze** [comment]
I also think so - my `solarpatrol/satellitejs` package is still there though I unregistered it.

I updated my project to use your Bower package - everything works fine. Thanks, man! :)

**Comment by shashwatak** [comment]
No, thank you! Really excited to have this project on bower =) I feel more integrated to the greater community.

**Comment by davidcalhoun** [comment]
Sweet!  Now folks can use this in Node.js as well.  :)

Thanks for these updates!

**Pull request merged**
